// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $api_v1_todos_id_ from "./routes/api/v1/todos/[id].ts";
import * as $api_v1_todos_index from "./routes/api/v1/todos/index.ts";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/api/v1/todos/[id].ts": $api_v1_todos_id_,
    "./routes/api/v1/todos/index.ts": $api_v1_todos_index,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
